# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protocols/common/FrameCommon.proto
# Protobuf Python Version: 5.27.0-rc1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    0,
    '-rc1',
    'protocols/common/FrameCommon.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"protocols/common/FrameCommon.proto\x12\x0eKmrServerFrame\x1a google/protobuf/descriptor.proto\"Z\n\x11\x43onfigMetaExample\x12\"\n\x08jsonName\x18\x01 \x01(\tB\x10\x8a\x97\"\x0c\x65xample.json\x12!\n\x07xlsName\x18\x02 \x01(\tB\x10\x92\x97\"\x0c\x65xample.xlsx:6\n\rdbRequiredKey\x12\x1d.google.protobuf.FieldOptions\x18\xd0\x86\x03 \x01(\x08:6\n\rdbOptionalKey\x12\x1d.google.protobuf.FieldOptions\x18\xd1\x86\x03 \x01(\x08:2\n\tconfigKey\x12\x1d.google.protobuf.FieldOptions\x18\xe1\xd4\x03 \x01(\x08:6\n\rfieldNoteName\x12\x1d.google.protobuf.FieldOptions\x18\xe2\xd4\x03 \x01(\t:9\n\x10\x63onfigServerOnly\x12\x1d.google.protobuf.FieldOptions\x18\xe4\xd4\x03 \x01(\x08:9\n\x10\x63onfigClientOnly\x12\x1d.google.protobuf.FieldOptions\x18\xc9\xdc\x03 \x01(\x08::\n\x11\x63onfigClientFText\x12\x1d.google.protobuf.FieldOptions\x18\xca\xdc\x03 \x01(\x08::\n\x11\x63onfigClientFName\x12\x1d.google.protobuf.FieldOptions\x18\xcb\xdc\x03 \x01(\x08:3\n\x08isConfig\x12\x1f.google.protobuf.MessageOptions\x18\xb1\xe4\x03 \x01(\x08:;\n\x12\x63onfigMetaJsonName\x12\x1d.google.protobuf.FieldOptions\x18\xf1\xa2\x04 \x01(\t:;\n\x12\x63onfigMetaXlsxName\x12\x1d.google.protobuf.FieldOptions\x18\xf2\xa2\x04 \x01(\t:9\n\x0c\x65numNoteName\x12!.google.protobuf.EnumValueOptions\x18\xd9\xaa\x04 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protocols.common.FrameCommon_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONFIGMETAEXAMPLE'].fields_by_name['jsonName']._loaded_options = None
  _globals['_CONFIGMETAEXAMPLE'].fields_by_name['jsonName']._serialized_options = b'\212\227\"\014example.json'
  _globals['_CONFIGMETAEXAMPLE'].fields_by_name['xlsName']._loaded_options = None
  _globals['_CONFIGMETAEXAMPLE'].fields_by_name['xlsName']._serialized_options = b'\222\227\"\014example.xlsx'
  _globals['_CONFIGMETAEXAMPLE']._serialized_start=88
  _globals['_CONFIGMETAEXAMPLE']._serialized_end=178
# @@protoc_insertion_point(module_scope)
